### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by ChristopherJohnston** [spliit-app/spliit#189]
@scastiel can you indicate when you might have time to review the growing backlog of great PRs and schedule the next release?

**Comment by ankit-kapur** [comment]
+1

**Comment by tedzards509** [comment]
Perhaps someone could fork and somehow merge all the features from the MRs so that there is a more modern version to do work on. Then people wouldn't have to bother with merge conflicts and people could self-host with all the cool new features already.

What scares me is the possibility of @scastiel not liking all the changes and fragmentation occuring.

**Comment by ChristopherJohnston** [comment]
1.11.0 released 5 October 2024
