### ISSUE TITLE
JSON export not working?

### ISSUE THREAD

**Issue by dmlls** [spliit-app/spliit#54]
Clicking on export as JSON opens a new tab but then no download is started.

I tried it on Firefox and Safari, on both I got the same behavior.

The server responds with an `HTTP 500`.

**Comment by scastiel** [comment]
@dmlls looking at the logs, it seems that it was because the group name included a special character, such as an emoji? I was able to reproduce the error in this situation.

**Comment by dmlls** [comment]
@scastiel that was the case indeed. The new file naming logic fixes it, although perhaps a timestamp could be added? This would be helpful to easily tell different backups apart.

**Comment by scastiel** [comment]
> perhaps a timestamp could be added? This would be helpful to easily tell different backups apart.

Good point, just added the date. Note that because of timezone issues, I had to use the UTC date. This means that if I’m in Montreal and download the file on Jan 23 at 11pm, the file will be named `2023-01-24`. It would be possible to improve this, but it might be a bit overkill here.

Also, I brought back the group name in the generated file name, thanks to [this NPM package](https://www.npmjs.com/package/content-disposition) 😉

**Comment by dmlls** [comment]
@scastiel that's amazing! Thanks a lot :)

> It would be possible to improve this, but it might be a bit overkill here.

I agree, like this looks great already.
