### ISSUE TITLE
Join group by URL in PWA mode

### ISSUE THREAD

**Issue by justcallmelarry** [spliit-app/spliit#55]
Maybe I'm missing something, but it seems that you cannot join groups (only create them) from an PWA app?
Installed the PWA on my iPhone and group page tells me to open a link with a group or create a new one, but I have no way of opening the link inside the PWA.

Maybe there could be a button which opens a box where you can paste the link or id of a group in order to get it to load in the PWA?

**Comment by scastiel** [comment]
I agree, it is annoying not being able to open a group in PWA mode. It is because of two limitations on iOS:

- you can’t share any storage between the PWA and the Safari-version of the app (so visiting a group in Safari doesn’t add it to the PWA’s recent groups)
- you can’t set up the links on a domain (e.g. spliit.app) to be opened in the PWA.

I like your suggestion:

> Maybe there could be a button which opens a box where you can paste the link or id of a group in order to get it to load in the PWA?

It could be a nice workaround to finally be able to use Spliit as a PWA on iOS 😉

**Comment by scastiel** [comment]
> Maybe there could be a button which opens a box where you can paste the link or id of a group in order to get it to load in the PWA?

Done ✅ 😃

**Comment by justcallmelarry** [comment]
@scastiel 🚤 !! Thanks a bunch!
