### ISSUE TITLE
Create from receipt preview shows wrong amount even though it is right on create page

### ISSUE THREAD

**Issue by RayBB** [spliit-app/spliit#87]
Shows .17 should show 16.88

Probs a small display error.

<details>
  <summary>Screenshots</summary>
  
  ![Screenshot_20240207-200952](https://github.com/spliit-app/spliit/assets/921217/2c6b5a9b-e613-41b7-9d8e-2ca71f899fdf)
![Screenshot_20240207-201054](https://github.com/spliit-app/spliit/assets/921217/5a28a43c-d437-481f-9eaa-ca814f2e3325)

  
</details> 

PS: On a side not, I feel that the receipt detector is not very good at detecting DD/MM/YYYY it usually assumes MM/DD/YYYY.
Might be nice to have either a setting for a preference or guess based on the language/location of the receipt or something like that.

**Comment by mertd** [comment]
I am also encountering the incorrect amount preview every time I try the receipt scanner.

Considering the current user journey adds two additional interactions and an incorrect amount preview, I would suggest to
1. simply remove the preview modal, **or**
2. fix the preview and add a button to save preview data as-is with otherwise default settings (split etc.)
